const uploadButton = document.getElementById("uploadButton");
const fileInput = document.getElementById("fileInput");
const preview = document.getElementById("preview");
const analyzeButton = document.getElementById("analyzeButton");
const result = document.getElementById("result");

let selectedFile = null;


// =========================
// UPLOAD BUTTON
// =========================

uploadButton.addEventListener("click", function () {
    fileInput.click();
});


// =========================
// FILE SELECT
// =========================

fileInput.addEventListener("change", function () {

    const file = fileInput.files[0];

    if (!file) {
        return;
    }

    selectedFile = file;

    // Purana result clear
    result.innerHTML = "";

    // Purana preview clear
    preview.innerHTML = "";

    // Sirf image allow
    if (!file.type.startsWith("image/")) {

        preview.innerHTML = `
            <p>
                Please select an image file.
            </p>
        `;

        analyzeButton.style.display = "none";
        uploadButton.style.display = "inline-block";

        selectedFile = null;

        return;
    }


    // =========================
    // IMAGE PREVIEW
    // =========================

    const image = document.createElement("img");

    image.src = URL.createObjectURL(file);

    image.style.maxWidth = "100%";
    image.style.maxHeight = "300px";
    image.style.borderRadius = "12px";

    preview.appendChild(image);


    // =========================
    // BUTTON CHANGES
    // =========================

    // Upload button hide
    uploadButton.style.display = "none";

    // Analyze button show
    analyzeButton.style.display = "block";

    // Analyze button center
    analyzeButton.style.margin = "15px auto 0";
});


// =========================
// ANALYZE BUTTON
// =========================

analyzeButton.addEventListener("click", async function () {

    if (!selectedFile) {
        return;
    }


    // Button disable while analyzing
    analyzeButton.disabled = true;

    analyzeButton.innerText = "Analyzing...";


    // Loading message
    result.innerHTML = `
        <h2>Analyzing...</h2>
        <p>Please wait while TruthLens checks the image.</p>
    `;


    try {

        // FormData create
        const formData = new FormData();

        formData.append("file", selectedFile);


        // Backend ko image bhejna
        const response = await fetch(
            "http://127.0.0.1:5000/analyze",
            {
                method: "POST",
                body: formData
            }
        );


        const data = await response.json();


        // Backend error
        if (!response.ok || !data.success) {

            throw new Error(
                data.error || "Analysis failed"
            );
        }


        // =========================
        // REAL MODEL RESULT
        // =========================

        let predictionsHTML = "";

        data.predictions.forEach(function (prediction) {

            const percentage =
                (prediction.score * 100).toFixed(1);

            predictionsHTML += `
                <p>
                    <strong>
                        ${prediction.label}
                    </strong>
                    : ${percentage}%
                </p>
            `;
        });


        result.innerHTML = `
            <h2>Analysis Result</h2>

            ${predictionsHTML}

            <p style="font-size:12px;">
                Result generated by the TruthLens AI model.
            </p>
        `;

    }


    catch (error) {

        console.error(error);

        result.innerHTML = `
            <h2>Analysis Failed</h2>

            <p>
                ${error.message}
            </p>

            <p style="font-size:12px;">
                Make sure the TruthLens backend is running.
            </p>
        `;

    }


    finally {

        // Button wapas normal
        analyzeButton.disabled = false;

        analyzeButton.innerText = "Analyze File";

    }

});